version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   
      - "9100:9001"   
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  producer:
    image: python:3.11
    container_name: producer
    volumes:
      - ./producer:/app
    working_dir: /app
    tty: true

  consumer:
    image: python:3.11
    container_name: consumer
    volumes:
      - ./consumer:/app
    working_dir: /app
    tty: true

  train:
    image: bitnami/spark:3.5.0
    container_name: train
    ports:
      - "8000:8000"
    volumes:
      - ./train:/app 
    working_dir: /app
    depends_on:
      - kafka
      - minio                      
    command: tail -f /dev/null

volumes:
  minio_data:
